name: "Lark Notification For Frontend"
description: "Send a Lark card notification depending on the card_type"
inputs:
  card_type:
    description: | 
      input type for Lark card builder

      You can use it to:
      - develop => (DEV, show commit messages)
      - default => (UAT, PRD, pipeline show services name in release_control)
      - matrix  => (*SUPPORT MATRIX ONLY*)(UAT, PRD, pipeline show services name in release_control)

    required: true
  
  service_name:
    description: "e.g. github.event.repository.name"
    required: true
  actor:
    description: "e.g. github.actor"
    required: true
  repository:
    description: "e.g. github.repository"
    required: true
  ref:
    description: "e.g. github.ref"
    required: false

  commit_messages:
    description: "(require for develop) e.g. steps.commit_messages.outputs.commit_messages"
    required: false
  tag:
   description: "(require for default, matrix) e.g. github.event.inputs.tag"
   required: false

runs:
  using: "composite"
  steps:
    - name: Install jq
      uses: dcarbone/install-jq-action@v3.1.1

      # develop 
    - name: (develop) Commit messages to bullet list
      if: inputs.card_type == 'develop'
      id: commit_messages
      shell: bash
      run: |-
        commit_messages=$(echo '${{ inputs.commit_messages }}' | jq -r '.[].message' | sed 's/^/- /')
        commit_messages_json=$(printf "%s\n" "$commit_messages" | jq -Rs 'gsub("- \n-"; "     - ")')
        echo "commit_messages=$commit_messages_json" >> $GITHUB_OUTPUT

      # develop
    - name: (develop) Notify to Lark
      if: inputs.card_type == 'develop'
      shell: bash
      env:
        SERVICE_NAME: ${{ inputs.service_name }}
        GITHUB_ACTOR: ${{ inputs.actor }}
        GITHUB_REF: ${{ inputs.ref }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
      run: |-
        cat <<EOF > payload.json
        {
          "msg_type": "interactive",
          "card": {
            "type": "template",
            "data": {
              "template_id": "ctp_AA4OuaEvBdMQ",
              "template_variable": {
                "env": "DEV",
                "service_name": "$SERVICE_NAME",
                "deployer": "$GITHUB_ACTOR",
                "version": "$GITHUB_REF",
                "service_url": "https://github.com/$GITHUB_REPOSITORY",
                "commit_messages": ${{ steps.commit_messages.outputs.commit_messages }}
              }
            }
          }
        }
        EOF

        echo "===== Payload JSON ====="
        cat payload.json
        echo "========================"

        RESPONSE=$(curl -s -X POST "https://open.larksuite.com/open-apis/bot/v2/hook/250af2fe-9532-41d5-bba0-05a1655e45e5" \
          -H "Content-Type: application/json" \
          -d @payload.json)

        echo "Lark response: $RESPONSE"
        
      # default
    - name: (default) Notify to Lark
      if: inputs.card_type == 'default'
      shell: bash
      env:
        SERVICE_NAME: ${{ inputs.service_name }}
        GITHUB_ACTOR: ${{ inputs.actor }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
        TAG: ${{ inputs.tag }}
      run: |-
        service_lists="["
        while read -r line; do
          SERVICE_NAME_VAL=$(awk -F, '{print $1}' <<< "$line" | tr -d '[:space:]')
          VERSION=$(awk -F, '{print $2}' <<< "$line" | tr -d '[:space:]')
          if [ "$SERVICE_NAME_VAL" == "SERVICE" ]; then
            continue
          fi
          service_lists+="{\"service_name\": \"$SERVICE_NAME_VAL\", \"version\": \"$VERSION\"},"
        done < "helm-chart/release_control_content.csv"
        service_lists="${service_lists%,}"
        service_lists+="]"

        echo "Check service_lists."
        echo $service_lists

        cat <<EOF > payload.json
        {
          "msg_type": "interactive",
          "card": {
            "type": "template",
            "data": {
              "template_id": "ctp_AA48N2uQ1sNH",
              "template_variable": {
                "env": "UAT",
                "app_version": "$TAG",
                "deployer": "$GITHUB_ACTOR",
                "service_lists": $service_lists
              }
            }
          }
        }
        EOF

        echo "===== Payload JSON ====="
        cat payload.json
        echo "========================"

        RESPONSE=$(curl -s -X POST "https://open.larksuite.com/open-apis/bot/v2/hook/250af2fe-9532-41d5-bba0-05a1655e45e5" \
          -H "Content-Type: application/json" \
          -d @payload.json)

        echo "Lark response: $RESPONSE"

    - name: (matrix) Notify to Lark
      if: inputs.card_type == 'matrix'
      shell: bash
      env:
        GITHUB_ACTOR: ${{ inputs.actor }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
        ALL_SERVICE: ${{ inputs.service_name }}
        TAG: ${{ inputs.tag }}
      run: |-
        echo "$ALL_SERVICE" | jq -c '.' | jq -r '.[]' > modules.txt

        service_lists="["
        while read -r module; do
          echo "Processing module: $module"
          if [ ! -f "helm-chart/release_control_admin_web_${module}.csv" ]; then
            echo "File helm-chart/release_control_admin_web_${module}.csv not found!"
            continue
          fi

          while read -r line; do
            SERVICE_NAME=$(awk -F, '{print $1}' <<< "$line" | tr -d '[:space:]')
            VERSION=$(awk -F, '{print $2}' <<< "$line" | tr -d '[:space:]')
            if [ "$SERVICE_NAME" == "SERVICE" ]; then
              continue
            fi
            service_lists+="{\"service_name\": \"$SERVICE_NAME\", \"version\": \"$VERSION\"},"
          done < "helm-chart/release_control_admin_web_${module}.csv"
        done < modules.txt

        # Remove trailing comma
        service_lists="${service_lists%,}"
        service_lists+="]"

        echo "Check service_lists."
        echo $service_lists

        cat <<EOF > payload.json
        {
          "msg_type": "interactive",
          "card": {
            "type": "template",
            "data": {
              "template_id": "ctp_AA48N2uQ1sNH",
              "template_variable": {
                "env": "UAT",
                "app_version": "$TAG",
                "deployer": "$GITHUB_ACTOR",
                "service_lists": $service_lists
              }
            }
          }
        }
        EOF

        echo "===== Payload JSON ====="
        cat payload.json
        echo "========================"

        RESPONSE=$(curl -s -X POST "https://open.larksuite.com/open-apis/bot/v2/hook/250af2fe-9532-41d5-bba0-05a1655e45e5" \
          -H "Content-Type: application/json" \
          -d @payload.json)

        echo "Lark response: $RESPONSE"